apiVersion: apps/v1
kind: Deployment
metadata:
  name: forumfrontend
  labels:
    app: forumfrontend
spec:
  selector:
    matchLabels:
      app: forumfrontend
  template:
    metadata:
      labels:
        app: forumfrontend
    spec:
      containers:
        - image: {{ .Values.appimage }}
          name: forumfrontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: forumfrontend-svc
spec:
  type: NodePort
  selector:
    app: forumfrontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000